version: '3'

services:
  console:
    build: .
    image: coisa/console
    volumes:
      - ./:/app
    env_file:
      # defaults environments
      - .env.example
      # overwrites & secrets environments
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:5.6
    env_file:
      - .env.example
      - .env
